apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "helse-sprik"
  namespace: "helse-sprik"
  labels:
    team: "helse-sprik"
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readyness:
    path: isready
    initialDelay: 5
  replicas:
    min: 1
    max: 2
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        diskAuthorize: true
        databases:
          - name: helse-sprik
            envVarPrefix: DATABASE
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi
  ingresses:
    - https://helse-sprik.intern.dev.nav.no